backend = "glx";
vsync = true;
use-damage = true;

shadow = true;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.6;
shadow-color = "#100e23";
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'dmenu'",
  "_GTK_FRAME_EXTENTS@:c"
];

fading = true;
fade-delta = 8;
fade-in-step = 0.06;
fade-out-step = 0.06;

active-opacity = 1.0;
inactive-opacity = 0.88;
opacity-rule = [
  "95:class_g = 'kitty'",
  "100:class_g = 'Emacs'",
  "100:class_g = 'virt-manager'"
];

blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;
blur-background-exclude = [
  "class_g = 'slop'"
];

corner-radius = 8;
rounded-corners-exclude = [
  "class_g = 'dwm'",
  "class_g = 'dmenu'"
];
