confirm_os_window_close 0
enabled_layouts tall,*
window_padding_width 5
font_family SpaceMono Nerd Font
font_size 10.0
background_opacity 1.0
tab_bar_style powerline

include themes/challenger-deep.conf
