# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-471f6f55-05a8-4a89-97bb-6f6afd2b5d97";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-471f6f55-05a8-4a89-97bb-6f6afd2b5d97".device = "/dev/disk/by-uuid/471f6f55-05a8-4a89-97bb-6f6afd2b5d97";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BA30-567C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-6d2075cf-29b4-4a81-bac0-bd8bd804dff3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
