# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.

CHOST="x86_64-pc-linux-gnu"

COMMON_FLAGS="-O2 -pipe -march=x86-64-v3"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

PYTHON_TARGETS="python3_14 python3_13"
PYTHON_SINGLE_TARGET="python3_14"

CPU_FLAGS_X86="aes avx avx2 avx_vnni bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 ssse3 vpclmulqdq"

VIDEO_CARDS="intel"

MAKEOPTS="-j8"

FEATURES="getbinpkg binpkg-request-signature"

EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --getbinpkg=y --binpkg-respect-use=y --usepkg-exclude='sys-kernel/gentoo-sources sys-kernel/vanilla-sources'"

ACCEPT_LICENSE="*"

USE="bluetooth dbus elogind opengl pipewire pipewire-alsa policykit pulseaudio udev wayland -systemd"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="https://in.mirrors.cicku.me/gentoo/ \
    https://mirrors.nxtgen.com/gentoo-mirror/gentoo-source/ \
    https://gentoo.mirrors.ovh.net/gentoo-distfiles/ \
    https://ariel.in.ext.planetunix.net/pub/gentoo/ \
    https://jp.mirrors.cicku.me/gentoo/ \
    https://mirror.hashy0917.net/gentoo/ \
    https://ftp.iij.ad.jp/pub/linux/gentoo/ \
    https://ftp.jaist.ac.jp/pub/Linux/Gentoo/ \
    https://repo.jing.rocks/gentoo \
    https://kale.jp.ext.planetunix.net/pub/gentoo/ \
    https://ftp.riken.jp/Linux/gentoo/ \
    https://us.mirrors.cicku.me/gentoo/ \
    https://mirror.clarkson.edu/gentoo/ \
    http://www.gtlib.gatech.edu/pub/gentoo \
    https://mirrors.kernel.org/gentoo/ \
    https://mirror.leaseweb.com/gentoo/ \
    https://mirrors.mit.edu/gentoo-distfiles/ \
    https://mirror.cs.odu.edu/ \
    https://gentoo.osuosl.org/ \
    https://mirror.planetunix.net/pub/gentoo/ \
    https://mirror.rackspace.com/gentoo/ \
    https://mirrors.rit.edu/gentoo/ \
    https://mirror.servaxnet.com/gentoo/ \
    https://mirror.umd.edu/gentoo/ \
    http://gentoo-mirror.flux.utah.edu/"
