# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-31b925a3-059a-46cf-bc69-75cbbc4a9301";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-31b925a3-059a-46cf-bc69-75cbbc4a9301".device = "/dev/disk/by-uuid/31b925a3-059a-46cf-bc69-75cbbc4a9301";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6ED0-DE8A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-347acf17-4b7f-4401-9314-2006643736cc"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
